### ISSUE TITLE
field images pada analytic yang membutuhkan hanya 1 gambar

### ISSUE THREAD

**Issue by gregoriusjimmy** [nodefluxio/inlabs#9]
kenapa analytic yang hanya membutuhkan 1 gambar saja tidak menggunakan field image dengan tipe string instead of images dengan tipe array?

**Comment by sonadztux** [comment]
Yes it is. Kebingungan gue juga sama soal ini wk. Gue coba input multiple image dapet response 400 Bad Request padahal key inputannya dalam bentuk array. Why?

**Comment by lazuardyk** [comment]
Kayanya ada hubungannya ke limit nya sih,
Karena utk sekarang aja ada limit query per secondnya:
https://docs.nodeflux.io/visionaire-cloud/fundamentals/limits#query-per-second
Kayanya bakal berat beban servernya kalo bisa multiple image dan prosesnya juga bakal lama.
CMIIW

**Comment by gregoriusjimmy** [comment]
@lazuardyk maksud gw klo memang cuman dibutuhkan 1 gambar kenapa engga yang tadinya gini
```json
{
  "images": [
    "{INSERT_JPEG_IMAGE_AS_BASE64_STRING_FOR_YOUR_SELFIE}"
  ]
}
```
jadi 
```json
{
  "image": "{INSERT_JPEG_IMAGE_AS_BASE64_STRING_FOR_YOUR_SELFIE}"
}
```

**Comment by lazuardyk** [comment]
> @lazuardyk maksud gw klo memang cuman dibutuhkan 1 gambar kenapa engga yang tadinya gini
> 
> ```json
> {
>   "images": [
>     "{INSERT_JPEG_IMAGE_AS_BASE64_STRING_FOR_YOUR_SELFIE}"
>   ]
> }
> ```
> 
> jadi
> 
> ```json
> {
>   "image": "{INSERT_JPEG_IMAGE_AS_BASE64_STRING_FOR_YOUR_SELFIE}"
> }
> ```

ohiya bener juga haha sorry salah nangkep

**Comment by asyafalni** [comment]
Ini udah sempet dijelasin sama kris ya.. lebih ke uniform body request aja. karna hakikatnya `array` dengan isi 1 itu valid. Sedangkan analytic kita punya beragam tipe, ada yang terkadang membutuhkan image lebih dari 1, jadi buat penyeragaman kita pake field `images: []`.
